/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import proyecto.grafos.Grafo;
import proyecto.grafos.Vertice;
import proyecto.grafos.TxtFile;
import proyecto.grafos.GraphPopup;
import org.graphstream.graph.Graph;
import org.graphstream.graph.implementations.MultiGraph;
import org.graphstream.ui.view.Viewer;
import org.graphstream.ui.swing_viewer.SwingViewer;
import org.graphstream.ui.swing_viewer.ViewPanel;
import javax.swing.*;
/**
 *
 * @author Admin
 */
public class Interfaz extends javax.swing.JFrame {

    Grafo Grafito;
    int VertxCount;
    TxtFile Archivo;

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.Archivo = new TxtFile();
        Grafo nuevoGrafo=Archivo.openFileViaExplorer();
        if (nuevoGrafo!=null){
            this.Grafito = new Grafo();
        }else{
            this.Grafito=new Grafo();
        }
        this.VertxCount = 0;
    }
    
    

    public Boolean isEmpty(String str) {
        return (str == null || str.length() == 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IconUser = new javax.swing.JLabel();
        Button_Ver_Grafo = new javax.swing.JButton();
        Texto_Nombre = new javax.swing.JLabel();
        TextField_Agregar_User = new javax.swing.JTextField();
        Button_Agregar_Users = new javax.swing.JButton();
        TextField_Eliminar_User = new javax.swing.JTextField();
        Button_Eliminar_Users = new javax.swing.JButton();
        IconPuente = new javax.swing.JLabel();
        Button_Lista_Puentes = new javax.swing.JButton();
        Texto_Usuarios = new javax.swing.JLabel();
        Decor_Usuarios = new javax.swing.JLabel();
        TextField_Usuario1 = new javax.swing.JTextField();
        TextField_Usuario2 = new javax.swing.JTextField();
        TextField_Peso = new javax.swing.JTextField();
        Texto_Peso = new javax.swing.JLabel();
        Decor_Peso = new javax.swing.JLabel();
        Button_Eliminar_Puente = new javax.swing.JButton();
        Button_Agregar_Puente = new javax.swing.JButton();
        IconIsla = new javax.swing.JLabel();
        Texto_Cantidad_Islas = new javax.swing.JLabel();
        Button_DFS = new javax.swing.JButton();
        Button_BFS = new javax.swing.JButton();
        Contador_DFS = new javax.swing.JLabel();
        Contador_BFS = new javax.swing.JLabel();
        Texto_Cantidad_Islas1 = new javax.swing.JLabel();
        Texto_Cantidad_Islas2 = new javax.swing.JLabel();
        Salir = new javax.swing.JButton();
        EsPuente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaPuentes = new javax.swing.JTextArea();
        Grafo_Fondo = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1.png"))); // NOI18N
        getContentPane().add(IconUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 80, 80));

        Button_Ver_Grafo.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Button_Ver_Grafo.setText("Ver grafo");
        Button_Ver_Grafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Ver_GrafoActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Ver_Grafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 490, 140, 30));

        Texto_Nombre.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Texto_Nombre.setText("Nombre");
        Texto_Nombre.setToolTipText("");
        getContentPane().add(Texto_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 60, 20));

        TextField_Agregar_User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_Agregar_UserActionPerformed(evt);
            }
        });
        getContentPane().add(TextField_Agregar_User, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 90, 30));

        Button_Agregar_Users.setBackground(new java.awt.Color(195, 205, 196));
        Button_Agregar_Users.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Button_Agregar_Users.setText("Agregar User");
        Button_Agregar_Users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Agregar_UsersActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Agregar_Users, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 140, 30));

        TextField_Eliminar_User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_Eliminar_UserActionPerformed(evt);
            }
        });
        getContentPane().add(TextField_Eliminar_User, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 90, 30));

        Button_Eliminar_Users.setBackground(new java.awt.Color(195, 205, 196));
        Button_Eliminar_Users.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Button_Eliminar_Users.setText("Eliminar User");
        Button_Eliminar_Users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Eliminar_UsersActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Eliminar_Users, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 140, 30));

        IconPuente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2.png"))); // NOI18N
        getContentPane().add(IconPuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 80, 80));

        Button_Lista_Puentes.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Button_Lista_Puentes.setText("Actualizar lista");
        Button_Lista_Puentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Lista_PuentesActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Lista_Puentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 490, 140, 30));

        Texto_Usuarios.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Texto_Usuarios.setText("Usuarios");
        Texto_Usuarios.setToolTipText("");
        getContentPane().add(Texto_Usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, 20));

        Decor_Usuarios.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Decor_Usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/6.png"))); // NOI18N
        Decor_Usuarios.setToolTipText("");
        getContentPane().add(Decor_Usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 80, 20));

        TextField_Usuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_Usuario1ActionPerformed(evt);
            }
        });
        getContentPane().add(TextField_Usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 90, 30));

        TextField_Usuario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_Usuario2ActionPerformed(evt);
            }
        });
        getContentPane().add(TextField_Usuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 90, 30));

        TextField_Peso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_PesoActionPerformed(evt);
            }
        });
        getContentPane().add(TextField_Peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 90, 30));

        Texto_Peso.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Texto_Peso.setText("Peso");
        Texto_Peso.setToolTipText("");
        getContentPane().add(Texto_Peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 30, 20));

        Decor_Peso.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Decor_Peso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/6.png"))); // NOI18N
        Decor_Peso.setToolTipText("");
        getContentPane().add(Decor_Peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 80, 20));

        Button_Eliminar_Puente.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Button_Eliminar_Puente.setText("Eliminar puente");
        Button_Eliminar_Puente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Eliminar_PuenteActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Eliminar_Puente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 130, 30));

        Button_Agregar_Puente.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Button_Agregar_Puente.setText("Agregar puente");
        Button_Agregar_Puente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Agregar_PuenteActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Agregar_Puente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 130, 30));

        IconIsla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/3.png"))); // NOI18N
        getContentPane().add(IconIsla, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 80, 80));

        Texto_Cantidad_Islas.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Texto_Cantidad_Islas.setText("Islas:");
        Texto_Cantidad_Islas.setToolTipText("");
        getContentPane().add(Texto_Cantidad_Islas, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, 40, 30));

        Button_DFS.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Button_DFS.setText("Método DFS");
        Button_DFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_DFSActionPerformed(evt);
            }
        });
        getContentPane().add(Button_DFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 120, 30));

        Button_BFS.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Button_BFS.setText("Método BFS");
        Button_BFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_BFSActionPerformed(evt);
            }
        });
        getContentPane().add(Button_BFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 120, 30));

        Contador_DFS.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Contador_DFS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Contador_DFS.setText("0");
        Contador_DFS.setToolTipText("");
        getContentPane().add(Contador_DFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 60, 20, 30));

        Contador_BFS.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Contador_BFS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Contador_BFS.setText("0");
        Contador_BFS.setToolTipText("");
        getContentPane().add(Contador_BFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 100, 20, 30));

        Texto_Cantidad_Islas1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Texto_Cantidad_Islas1.setText("Verificar Cantidad de islas");
        Texto_Cantidad_Islas1.setToolTipText("");
        getContentPane().add(Texto_Cantidad_Islas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 170, 20));

        Texto_Cantidad_Islas2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Texto_Cantidad_Islas2.setText("Islas:");
        Texto_Cantidad_Islas2.setToolTipText("");
        getContentPane().add(Texto_Cantidad_Islas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 60, 40, 30));

        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir.png"))); // NOI18N
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 60, 60));

        EsPuente.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        EsPuente.setText("Verificar si son puentes");
        EsPuente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EsPuenteActionPerformed(evt);
            }
        });
        getContentPane().add(EsPuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 180, 30));

        ListaPuentes.setColumns(20);
        ListaPuentes.setRows(5);
        jScrollPane1.setViewportView(ListaPuentes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 280, 280));

        Grafo_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo Grafo_1.png"))); // NOI18N
        getContentPane().add(Grafo_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo Principal.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextField_PesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_PesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_PesoActionPerformed

    private void Button_Eliminar_UsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Eliminar_UsersActionPerformed
        try {
            
            if (isEmpty(TextField_Eliminar_User.getText())) {
                System.out.println("No se ha introducido ninguna entrada");
            } else if (TextField_Eliminar_User.getText().equals(" ")) {
                System.out.println("No se pueden introducir espacios");
            } else {
                String Username = TextField_Eliminar_User.getText();
                Grafito.eliminarVertice(Grafito.findVertice(Username));
                Log PopUp = new Log();
                PopUp.getTexto().setText("Usuario eliminado");
                PopUp.setVisible(true);
            }

        } catch (Exception e) {
            System.out.println("(ADVERTENCIA: Algo ha salido mal al eliminar un User)");
        }
    }//GEN-LAST:event_Button_Eliminar_UsersActionPerformed

    private void TextField_Eliminar_UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_Eliminar_UserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_Eliminar_UserActionPerformed

    private void Button_BFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_BFSActionPerformed
        try {
            Contador_BFS.setText(Integer.toString(Grafito.numIslasBFS()));
        } catch (Exception e) {
            System.out.println("(ADVERTENCIA: Algo ha salido mal al contar islas usando BFS)");
        }
    }//GEN-LAST:event_Button_BFSActionPerformed

    private void Button_Agregar_UsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Agregar_UsersActionPerformed
        try {
            if (isEmpty(TextField_Agregar_User.getText())) {
                System.out.println("No se ha introducido ninguna entrada");
            } else if (TextField_Agregar_User.getText().equals(" ")) {
                System.out.println("No se pueden introducir espacios");
            } else if (Grafito.ExisteUsername(TextField_Agregar_User.getText())) {
                System.out.println("Nombre de usuario registrado, intente con otro");
            } else {
                String Username = TextField_Agregar_User.getText();
                Grafito.agregarVertice(VertxCount, Username);
                VertxCount++;
                Log PopUp = new Log();
                PopUp.getTexto().setText("Usuario agregado");
                PopUp.setVisible(true);
                //Grafito.ListaVertices();
            }
        } catch (Exception e) {
            System.out.println("(ADVERTENCIA: Algo ha salido mal al agregar un User)");
            System.out.println(e);
        }
    }//GEN-LAST:event_Button_Agregar_UsersActionPerformed

    private void Button_Lista_PuentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Lista_PuentesActionPerformed
        try {
            if (Grafito.isEmpty()) {
                System.out.println("El grafo no tiene arcos por lo que no se actualizo la lista\n");
            } else {
                int length = ListaPuentes.getText().length();
                ListaPuentes.replaceRange("", 0, length);
                ListaPuentes.append("Puentes:\n\n");
                for (int x = 0; x < Grafito.getNumNodos(); x++) {
                    for (int i = 0; i < Grafito.getNumNodos(); i++) {
                        if (Grafito.esPuente(x, i)) {
                            Vertice User1 = Grafito.findVertice(x);
                            Vertice User2 = Grafito.findVertice(i);
                            ListaPuentes.append("Username: " + User1.getUsername() + "(" + User1.getId() + ")" + ", Username: " + User2.getUsername() + "(" + User2.getId() + ")" + ", Peso: " + Grafito.getMatrizAd()[x][i] + "\n");
                        }
                    }
                }
            }
            //Grafito.ListaPuentes(); (Lo use para testear)
        } catch (Exception e) {
            System.out.println("(ADVERTENCIA: Algo ha salido mal dentro de la lista de puentes)");
            System.out.println(e);
        }
    }//GEN-LAST:event_Button_Lista_PuentesActionPerformed

    private void TextField_Agregar_UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_Agregar_UserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_Agregar_UserActionPerformed

    private void TextField_Usuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_Usuario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_Usuario1ActionPerformed

    private void TextField_Usuario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_Usuario2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_Usuario2ActionPerformed

    private void Button_Agregar_PuenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Agregar_PuenteActionPerformed
        try {
            //Necesito verificar que todas las casillas tengan un texto
            if (isEmpty(TextField_Usuario1.getText()) || isEmpty(TextField_Usuario2.getText()) || isEmpty(TextField_Peso.getText())) {
                System.out.println("No se ha introducido ninguna entrada");
            } else if (TextField_Usuario1.getText().equals(" ") || TextField_Usuario2.getText().equals(" ") || TextField_Peso.getText().equals(" ")) {
                System.out.println("No se pueden introducir espacios");
            } else if (Grafito.findVertice(TextField_Usuario1.getText()) == null || Grafito.findVertice(TextField_Usuario2.getText()) == null) {
                System.out.println("Alguno de los vertices introducidos no existe");
            } else {
                Grafito.agregarArco(Grafito.findVertice(TextField_Usuario1.getText()).getNumVertice(), Grafito.findVertice(TextField_Usuario2.getText()).getNumVertice(), Integer.parseInt(TextField_Peso.getText()));
                //Contador_BFS.setText(Integer.toString(Grafito.numIslasBFS()));
                //Contador_DFS.setText(Integer.toString(Grafito.numIslas()));
                Log_1 PopUp = new Log_1();
                PopUp.getTexto().setText("Puente agregado");
                PopUp.setVisible(true);

            }
        } catch (NumberFormatException e) {
            System.out.println("(ADVERTENCIA: Algo ha salido mal al Agregar un puente)");
            System.out.println(e);
        }
    }//GEN-LAST:event_Button_Agregar_PuenteActionPerformed

    private void Button_DFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_DFSActionPerformed
        try {
            Contador_DFS.setText(Integer.toString(Grafito.numIslas()));
        } catch (Exception e) {
            System.out.println("ADVERTENCIA: Algo ha salido mal");
        }
    }//GEN-LAST:event_Button_DFSActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        Archivo.printFileViaExplorer(Grafito);
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void Button_Eliminar_PuenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Eliminar_PuenteActionPerformed
        try {
            //Necesito verificar que todas las casillas tengan un texto
            if (isEmpty(TextField_Usuario1.getText()) || isEmpty(TextField_Usuario2.getText())) {
                System.out.println("No se ha introducido ninguna entrada en los usuarios");
            } else if (TextField_Usuario1.getText().equals(" ") || TextField_Usuario2.getText().equals(" ") || TextField_Peso.getText().equals(" ")) {
                System.out.println("No se pueden introducir espacios");
            } else if (Grafito.findVertice(TextField_Usuario1.getText()) == null || Grafito.findVertice(TextField_Usuario2.getText()) == null) {
                System.out.println("Alguno de los vertices introducidos no existe");
            } else {
                if (isEmpty(TextField_Peso.getText()) == false) {
                    System.out.println("El peso agregado no se toma en consideración para eliminar puentes");
                }
                Grafito.agregarArco(Grafito.findVertice(TextField_Usuario1.getText()).getNumVertice(), Grafito.findVertice(TextField_Usuario2.getText()).getNumVertice(), 0);
                //Contador_BFS.setText(Integer.toString(Grafito.numIslasBFS()));
                //Contador_DFS.setText(Integer.toString(Grafito.numIslas()));
                Log_1 PopUp = new Log_1();
                PopUp.getTexto().setText("Puente eliminado");
                PopUp.setVisible(true);
            }
        } catch (NumberFormatException e) {
            System.out.println("(ADVERTENCIA: Algo ha salido mal al Agregar un puente)");
            System.out.println(e);
        }
    }//GEN-LAST:event_Button_Eliminar_PuenteActionPerformed

    private void Button_Ver_GrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Ver_GrafoActionPerformed
        GraphPopup Popup=new GraphPopup(Grafito);
        Popup.setVisible(true);
    }//GEN-LAST:event_Button_Ver_GrafoActionPerformed

    private void EsPuenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EsPuenteActionPerformed
        try{
            if (Grafito.esPuente(Grafito.findVertice(TextField_Usuario1.getText()).getId(), Grafito.findVertice(TextField_Usuario2.getText()).getId())){
                Log_1 PopUp = new Log_1();
                PopUp.getTexto().setText("Es puente");
                PopUp.setVisible(true);
            }else{
                Log_1 PopUp = new Log_1();
                PopUp.getTexto().setText("No es puente");
                PopUp.setVisible(true);
            }
            
        }catch (Exception e){
            System.out.println("Algo salio mal");
        }
    }//GEN-LAST:event_EsPuenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Agregar_Puente;
    private javax.swing.JButton Button_Agregar_Users;
    private javax.swing.JButton Button_BFS;
    private javax.swing.JButton Button_DFS;
    private javax.swing.JButton Button_Eliminar_Puente;
    private javax.swing.JButton Button_Eliminar_Users;
    private javax.swing.JButton Button_Lista_Puentes;
    private javax.swing.JButton Button_Ver_Grafo;
    private javax.swing.JLabel Contador_BFS;
    private javax.swing.JLabel Contador_DFS;
    private javax.swing.JLabel Decor_Peso;
    private javax.swing.JLabel Decor_Usuarios;
    private javax.swing.JButton EsPuente;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Grafo_Fondo;
    private javax.swing.JLabel IconIsla;
    private javax.swing.JLabel IconPuente;
    private javax.swing.JLabel IconUser;
    private javax.swing.JTextArea ListaPuentes;
    private javax.swing.JButton Salir;
    private javax.swing.JTextField TextField_Agregar_User;
    private javax.swing.JTextField TextField_Eliminar_User;
    private javax.swing.JTextField TextField_Peso;
    private javax.swing.JTextField TextField_Usuario1;
    private javax.swing.JTextField TextField_Usuario2;
    private javax.swing.JLabel Texto_Cantidad_Islas;
    private javax.swing.JLabel Texto_Cantidad_Islas1;
    private javax.swing.JLabel Texto_Cantidad_Islas2;
    private javax.swing.JLabel Texto_Nombre;
    private javax.swing.JLabel Texto_Peso;
    private javax.swing.JLabel Texto_Usuarios;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
